title: Web Prolog and the Prolog Web
description: A collection of resources referred to during the talks
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
