title: Web Prolog and the Prolog Web
description: A collection of resources referenced during my talk at the Scryer Meetup 2024
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
